apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: ${ELASTICSEARCH_PORT}
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
