.catalog:
  name: Heapster Grafana InfluxDB V4
  version: monitoring-influxdb-grafana-v4
  description: A cluster-wide aggregator of monitoring and event data.
  questions:
    - variable: "GRAFANA_PORT"
      label: "Node port for Grafana"
      required: true
      default: 30804
      type: "int"
    - variable: "INFLUXDB_PORT"
      label: "Node port for Influxdb"
      required: true
      default: 30805
      type: "int"
