kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  labels:
    heritage: helm
    provider: spark
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: index.tenxcloud.com/google_containers/zeppelin:v0.5.5_v3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m

