apiVersion: v1
kind: Service
metadata:
  name: ${MYSQL_MASTER_NAME}
  labels:
    name: ${MYSQL_MASTER_NAME}
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: ${MYSQL_MASTER_NAME}
