apiVersion: v1
kind: ReplicationController
metadata:
  name: ${MYSQL_SLAVE_NAME}
  labels:
    name: ${MYSQL_SLAVE_NAME}
spec:
  replicas: 1
  selector:
    name: ${MYSQL_SLAVE_NAME}
  template:
    metadata:
      labels:
        name: ${MYSQL_SLAVE_NAME}
    spec:
      containers:
      - name: db-slave
        image: d.qianyilc.com/docker_images/qianyisrv-mysql:5.7
        env:
        - name: MYSQL_MASTER
          value: ${MYSQL_MASTER_NAME}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        emptyDir: {}
