apiVersion: v1
kind: Service
metadata:
  name: ${REDIS_MASTER_NAME}
  labels:
    name: ${REDIS_MASTER_NAME}
spec:
  ports:
    # the port that this service should serve on
  - port: 7501
    targetPort: 7501
  selector:
    name: ${REDIS_MASTER_NAME}
