apiVersion: v1
kind: ReplicationController
metadata:
  name: ${REDIS_MASTER_NAME}
  labels:
    name: ${REDIS_MASTER_NAME}
spec:
  replicas: 1
  selector:
    name: ${REDIS_MASTER_NAME}
  template:
    metadata:
      labels:
        name: ${REDIS_MASTER_NAME}
    spec:
      containers:
      - name: redis-master
        image: d.qianyilc.com/docker_images/qianyisrv-redis:1
        ports:
        - containerPort: 7501
        volumeMounts:
        - name: data
          mountPath: /data1/redis
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          exec:
            command: ["redis-cli", "-h", "127.0.0.1", "-p", "7501", "info"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: data
        emptyDir: {}
