apiVersion: v1
kind: ReplicationController
metadata:
  name: ${REDIS_MASTER_NAME}
  labels:
    name: ${REDIS_MASTER_NAME}
spec:
  replicas: 1
  selector:
    name: ${REDIS_MASTER_NAME}
  template:
    metadata:
      labels:
        name: ${REDIS_MASTER_NAME}
    spec:
      containers:
      - name: master
        image: d.qianyilc.com/docker_images/qianyisrv-redis:1
        ports:
        - containerPort: 7501
        volumeMounts:
        - name: data
          mountPath: /data1/redis
      volumes:
      - name: data
        emptyDir: {}
